# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09235aefbeaa6907d6bac86e453941a7c0ac5fa11cc7c7f9f7d4091b23758eadecf0a28d59bcc2570efb1adf7665e75d8de9c0401eaf9382ecf7c831269aad2e

test:
  secret_key_base: 29426cea0fcd5b9f0c427b6d9c70840dd073564cd58b61c7975127bb263d157860cca3b8f325af63683f628cce38af4976284043176144a01a82ffab3dd756a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
